# Azure Container Instances deployment template
# Use this for quick deployment to Azure

version: '3.8'

services:
  filestream-bot:
    image: your-dockerhub-username/filestream-bot:latest
    ports:
      - "8080:8080"
    environment:
      # Core Configuration
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - DATABASE_URL=${DATABASE_URL}
      
      # Multi-Bot System
      - MULTI_BOT_MODE=true
      - MULTITOKEN1=${MULTITOKEN1}
      - MULTITOKEN2=${MULTITOKEN2}
      - MULTITOKEN3=${MULTITOKEN3}
      - MULTITOKEN4=${MULTITOKEN4}
      - MULTITOKEN5=${MULTITOKEN5}
      - MULTITOKEN6=${MULTITOKEN6}
      - MULTITOKEN7=${MULTITOKEN7}
      
      # Azure Web Server Configuration
      - PORT=8080
      - BIND_ADDRESS=0.0.0.0
      - HAS_SSL=true
      - NO_PORT=true
      - FQDN=${AZURE_FQDN:-filestream.azurecontainer.io}
      
      # Channel Configuration
      - AUTH_CHANNEL=${AUTH_CHANNEL}
      - GENERATE_DOWNLOAD_LINKS=true
      - FLOG_CHANNEL=${FLOG_CHANNEL}
      - ULOG_CHANNEL=${ULOG_CHANNEL}
      - FORCE_SUB_ID=${FORCE_SUB_ID}
      - FORCE_SUB=true
      
      # Performance Settings
      - BOT_WORKERS=10
      - SESSION_NAME=StreamBot
      - FILE_EXPIRATION_TIME=3600
      - REQUEST_TIMEOUT=300
      
      # Custom Images
      - START_PIC=${START_PIC}
      - FILE_PIC=${FILE_PIC}
      - VERIFY_PIC=${VERIFY_PIC}
      
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Azure-specific configuration
# This file can be used with Azure Container Instances
# or Azure Container Apps for deployment
